// Joins the Temporal prelude's parts (the other .js files here, in name order) into
// ../temporal.js, the string codegen puts in front of a program that names Temporal.
//   node compiler/temporal/build.js
import fs from 'node:fs';
import path from 'node:path';

const dir = import.meta.dirname;
const parts = fs.readdirSync(dir).filter(name => /^\d\d-.*\.js$/.test(name)).sort();
const source = parts.map(name => fs.readFileSync(path.join(dir, name), 'utf8')).join('\n');
fs.writeFileSync(path.join(dir, '../temporal.js'),
  `// generated by temporal/build.js from temporal/*.js: edit those, then run it\nexport default ${JSON.stringify(source)};\n`);
console.log(`temporal.js: ${parts.length} parts, ${source.length} chars`);
