// Dragonbox, ported to C for Porffor's number-to-string (--dtoa=dragonbox, the default):
// the shortest decimal that round-trips to a binary64, and the closest such when there are
// several, as Number::toString wants it. From https://github.com/jk-jeon/dragonbox
// (include/dragonbox/dragonbox.h and subproject/simple/include/simple_dragonbox.h),
// binary64 and round-to-nearest only, with the compact cache (every 27th power of ten
// stored, the others recovered with a multiplication by a power of 5: about 600 bytes of
// tables, not 9.9 KB).
//
// Copyright 2020-2025 Junekey Jeon; simple_dragonbox.h copyright 2024-2025 Junekey Jeon,
// Toby Bell. Used under the Boost Software License, Version 1.0:
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

export const DRAGONBOX_C = `// Dragonbox (Junekey Jeon): the shortest decimal that round-trips to a binary64, and the
// closest such when there are several. Ported to C from https://github.com/jk-jeon/dragonbox
// (Boost Software License 1.0), binary64 and round-to-nearest only, with the compact cache
// (every 27th power of ten stored, the rest recovered with a multiplication by a power of 5).
typedef struct { uint64_t hi, lo; } porf_db_u128;

static inline porf_db_u128 porf_db_umul128(uint64_t x, uint64_t y) {
  const uint64_t a = x >> 32, b = (uint32_t)x, c = y >> 32, d = (uint32_t)y;
  const uint64_t ac = a * c, bc = b * c, ad = a * d, bd = b * d;
  const uint64_t mid = (bd >> 32) + (uint32_t)ad + (uint32_t)bc;
  return (porf_db_u128){ ac + (mid >> 32) + (ad >> 32) + (bc >> 32), (mid << 32) + (uint32_t)bd };
}
static inline uint64_t porf_db_umul128_hi(uint64_t x, uint64_t y) { return porf_db_umul128(x, y).hi; }

// the upper 128 bits of x * y (y 128 bits)
static inline porf_db_u128 porf_db_umul192_hi(uint64_t x, porf_db_u128 y) {
  porf_db_u128 r = porf_db_umul128(x, y.hi);
  const uint64_t add = porf_db_umul128_hi(x, y.lo);
  const uint64_t lo = r.lo + add;
  r.hi += lo < r.lo;
  r.lo = lo;
  return r;
}
// the lower 128 bits of x * y (y 128 bits)
static inline porf_db_u128 porf_db_umul192_lo(uint64_t x, porf_db_u128 y) {
  const porf_db_u128 hl = porf_db_umul128(x, y.lo);
  return (porf_db_u128){ x * y.hi + hl.hi, hl.lo };
}

static inline uint64_t porf_db_rotr(uint64_t n, unsigned r) { r &= 63; return (n >> r) | (n << ((64 - r) & 63)); }

// every 27th of the powers of ten 10^k, k from -292, rounded up to 128 bits
static const porf_db_u128 porf_db_cache[23] = {
  { 0xff77b1fcbebcdc4full, 0x25e8e89c13bb0f7bull },
  { 0xce5d73ff402d98e3ull, 0xfb0a3d212dc81290ull },
  { 0xa6b34ad8c9dfc06full, 0xf42faa48c0ea481full },
  { 0x86a8d39ef77164bcull, 0xae5dff9c02033198ull },
  { 0xd98ddaee19068c76ull, 0x3badd624dd9b0958ull },
  { 0xafbd2350644eeacfull, 0xe5d1929ef90898fbull },
  { 0x8df5efabc5979c8full, 0xca8d3ffa1ef463c2ull },
  { 0xe55990879ddcaabdull, 0xcc420a6a101d0516ull },
  { 0xb94470938fa89bceull, 0xf808e40e8d5b3e6aull },
  { 0x95a8637627989aadull, 0xdde7001379a44aa9ull },
  { 0xf1c90080baf72cb1ull, 0x5324c68b12dd6339ull },
  { 0xc350000000000000ull, 0x0000000000000000ull },
  { 0x9dc5ada82b70b59dull, 0xf020000000000000ull },
  { 0xfee50b7025c36a08ull, 0x02f236d04753d5b5ull },
  { 0xcde6fd5e09abcf26ull, 0xed4c0226b55e6f87ull },
  { 0xa6539930bf6bff45ull, 0x84db8346b786151dull },
  { 0x865b86925b9bc5c2ull, 0x0b8a2392ba45a9b3ull },
  { 0xd910f7ff28069da4ull, 0x1b2ba1518094da05ull },
  { 0xaf58416654a6babbull, 0x387ac8d1970027b3ull },
  { 0x8da471a9de737e24ull, 0x5ceaecfed289e5d3ull },
  { 0xe4d5e82392a40515ull, 0x0fabaf3feaa5334bull },
  { 0xb8da1662e7b00a17ull, 0x3d6a751f3b936244ull },
  { 0x95527a5202df0ccbull, 0x0f37801e0c43ebc9ull }
};

static porf_db_u128 porf_db_get_cache(int k) {
  const int index = (int)(((uint32_t)(k + 292) * 607u) >> 14);
  const int kb = index * 27 - 292;
  const int offset = k - kb;
  const porf_db_u128 base = porf_db_cache[index];
  if (offset == 0) return base;

  // 10^k = 10^kb * 5^offset * 2^offset, renormalized
  const int alpha = ((k * 76085) >> 15) - ((kb * 76085) >> 15);
  uint64_t pow5 = 1;
  for (int i = 0; i < offset; i++) pow5 *= 5;
  porf_db_u128 rec = porf_db_umul128(base.hi, pow5);
  const porf_db_u128 ml = porf_db_umul128(base.lo, pow5);
  const uint64_t lo = rec.lo + ml.hi;
  rec.hi += lo < rec.lo;
  rec.lo = lo;
  const uint64_t high_to_middle = rec.hi << (64 - alpha);
  const uint64_t middle_to_low = rec.lo << (64 - alpha);
  return (porf_db_u128){ (rec.lo >> alpha) | high_to_middle, ((ml.lo >> alpha) | middle_to_low) + 1 };
}

static void porf_db_remove_trailing_zeros(uint64_t* sig, int* exp) {
  uint64_t s = *sig;
  uint64_t r = porf_db_rotr(s * 28999941890838049ull, 8);
  int b = r < 184467440738ull;
  int n = b;
  s = b ? r : s;
  r = porf_db_rotr(s * 182622766329724561ull, 4);
  b = r < 1844674407370956ull;
  n = n * 2 + b;
  s = b ? r : s;
  r = porf_db_rotr(s * 10330176681277348905ull, 2);
  b = r < 184467440737095517ull;
  n = n * 2 + b;
  s = b ? r : s;
  r = porf_db_rotr(s * 14757395258967641293ull, 1);
  b = r < 1844674407370955162ull;
  n = n * 2 + b;
  s = b ? r : s;
  *sig = s;
  *exp += n;
}

// bits: a finite, nonzero binary64. Its shortest decimal is *sig * 10^*exp
static void porf_dragonbox(uint64_t bits, uint64_t* out_sig, int* out_exp) {
  const uint64_t significand = bits & ((1ull << 52) - 1);
  int exponent = (int)((bits >> 52) & 0x7ff);
  const int is_even = (significand & 1) == 0;
  uint64_t two_fc = significand * 2;

  if (exponent != 0) {
    exponent += -1023 - 52;
    if (two_fc == 0) {
      // shorter interval: the significand is a power of two
      const int minus_k = (exponent * 631305 - 261663) >> 21;
      const int beta = exponent + ((-minus_k * 1741647) >> 19);
      const porf_db_u128 cache = porf_db_get_cache(-minus_k);
      uint64_t xi = (cache.hi - (cache.hi >> 54)) >> (11 - beta);
      const uint64_t zi = (cache.hi + (cache.hi >> 53)) >> (11 - beta);
      if (!(exponent >= 2 && exponent <= 3)) xi++;

      uint64_t sig = porf_db_umul128_hi(zi, 1844674407370955162ull); // zi / 10
      if (sig * 10 >= xi) {
        int exp = minus_k + 1;
        porf_db_remove_trailing_zeros(&sig, &exp);
        *out_sig = sig;
        *out_exp = exp;
        return;
      }
      sig = ((cache.hi >> (10 - beta)) + 1) / 2;
      if ((sig & 1) && exponent == -77) sig--;
        else if (sig < xi) sig++;
      *out_sig = sig;
      *out_exp = minus_k;
      return;
    }
    two_fc |= 1ull << 53;
  } else {
    exponent = -1022 - 52;
  }

  // kappa = 2: 10^kappa <= delta < 10^(kappa + 1)
  const int minus_k = ((exponent * 315653) >> 20) - 2;
  const porf_db_u128 cache = porf_db_get_cache(-minus_k);
  const int beta = exponent + ((-minus_k * 1741647) >> 19);

  const uint64_t deltai = cache.hi >> (63 - beta);
  const porf_db_u128 z = porf_db_umul192_hi((two_fc | 1) << beta, cache);
  const uint64_t zi = z.hi;
  const int z_is_integer = z.lo == 0;

  // the larger divisor, 10^(kappa + 1)
  uint64_t sig = porf_db_umul128_hi(zi, 4722366482869645214ull) >> 8; // zi / 1000
  uint64_t r = zi - 1000 * sig;

  do {
    if (r < deltai) {
      // the right endpoint excluded when it has to be
      if ((r | (uint64_t)!z_is_integer | (uint64_t)is_even) == 0) {
        sig--;
        r = 1000;
        break;
      }
    } else if (r > deltai) {
      break;
    } else {
      // r == deltai: the fractional parts compared
      const porf_db_u128 x = porf_db_umul192_lo(two_fc - 1, cache);
      const int x_parity = ((x.hi >> (64 - beta)) & 1) != 0;
      const int x_is_integer = ((x.hi << beta) | (x.lo >> (64 - beta))) == 0;
      if (!(x_parity | (x_is_integer & is_even))) break;
    }
    int exp = minus_k + 3;
    porf_db_remove_trailing_zeros(&sig, &exp);
    *out_sig = sig;
    *out_exp = exp;
    return;
  } while (0);

  // the smaller divisor, 10^kappa
  sig *= 10;
  uint64_t dist = r - (deltai / 2) + 50;
  const int approx_y_parity = ((dist ^ 50) & 1) != 0;
  const uint32_t prod = (uint32_t)(dist * 656);
  const int divisible = (prod & 0xffff) < 656;
  dist = prod >> 16;
  sig += dist;

  if (divisible) {
    // y is zi - epsilon or one less: the parity tells which, and a tie takes the even one
    const porf_db_u128 y = porf_db_umul192_lo(two_fc, cache);
    const int y_parity = ((y.hi >> (64 - beta)) & 1) != 0;
    const int y_is_integer = ((y.hi << beta) | (y.lo >> (64 - beta))) == 0;
    if (y_parity != approx_y_parity) sig--;
      else if ((sig & 1) & y_is_integer) sig--;
  }
  *out_sig = sig;
  *out_exp = minus_k + 2;
}
`;
