// Generates compiler/case_tables.js: the C tables behind String.prototype.toUpperCase /
// toLowerCase (render.js's porf_case_convert), derived from the running Node's own case
// mapping (ICU's Unicode data). Rerun when Node's Unicode version moves:
//   node compiler/gen_case_tables.js
//
// Simple mappings are runs of code points shifted by one delta, every code point (stride
// 1) or every other one (stride 2: the alternating upper/lower blocks). Mappings to more
// than one code point (ß -> SS, İ -> i̇) are listed one by one. Cased and Case_Ignorable
// are ranges, for the Final_Sigma rule (Σ lowercases to ς at the end of a word).
import fs from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const MAX = 0x10ffff;
const isSurrogate = cp => cp >= 0xd800 && cp <= 0xdfff;

const mappings = upper => {
  const simple = [], special = [];
  for (let cp = 0; cp <= MAX; cp++) {
    if (isSurrogate(cp)) continue;
    // Σ's lowercase depends on context: the runtime decides it (Final_Sigma)
    if (!upper && cp === 0x3a3) continue;
    const s = String.fromCodePoint(cp);
    const m = upper ? s.toUpperCase() : s.toLowerCase();
    if (m === s) continue;
    const cps = [ ...m ].map(c => c.codePointAt(0));
    if (cps.length === 1) simple.push([ cp, cps[0] - cp ]);
      else special.push([ cp, ...cps ]);
  }
  return { simple, special };
};

// runs of [start, count, stride, delta]: code points start, start + stride, … all shifted
// by delta, with nothing mapped in between (so runs never overlap and binary search works)
const toRuns = simple => {
  const mapped = new Set(simple.map(x => x[0]));
  const runs = [];
  let i = 0;
  while (i < simple.length) {
    const [ start, delta ] = simple[i];
    let stride = 1, count = 1;
    const next = simple[i + 1];
    if (next && next[1] === delta && next[0] === start + 2 && !mapped.has(start + 1)) stride = 2;
    while (i + count < simple.length) {
      const [ cp, d ] = simple[i + count];
      const want = start + count * stride;
      if (cp !== want || d !== delta) break;
      if (stride === 2 && mapped.has(want - 1)) break;
      count++;
    }
    runs.push([ start, count, stride, delta ]);
    i += count;
  }
  return runs;
};

// [start, end] ranges of the code points a property regex matches
const ranges = re => {
  const out = [];
  let start = -1;
  for (let cp = 0; cp <= MAX + 1; cp++) {
    const hit = cp <= MAX && !isSurrogate(cp) && re.test(String.fromCodePoint(cp));
    if (hit && start < 0) start = cp;
    if (!hit && start >= 0) { out.push([ start, cp - 1 ]); start = -1; }
  }
  return out;
};

const upper = mappings(true), lower = mappings(false);
const upperRuns = toRuns(upper.simple), lowerRuns = toRuns(lower.simple);
const cased = ranges(/^\p{Cased}$/u), ignorable = ranges(/^\p{Case_Ignorable}$/u);

const runRows = runs => runs.map(([ s, n, st, d ]) => `{${s},${n},${st},${d}}`).join(',');
const specialRows = list => list.map(x => `{${[ ...x, 0, 0, 0 ].slice(0, 4).join(',')}}`).join(',');
const rangeRows = list => list.map(([ s, e ]) => `{${s},${e}}`).join(',');

const c = `// generated by compiler/gen_case_tables.js from Node ${process.versions.node} (Unicode ${process.versions.unicode}): do not edit
typedef struct { u32 start; u16 count; u8 stride; i32 delta; } porf_case_run;
static const porf_case_run porf_upper_runs[${upperRuns.length}] = {${runRows(upperRuns)}};
static const porf_case_run porf_lower_runs[${lowerRuns.length}] = {${runRows(lowerRuns)}};
static const u32 porf_upper_special[${upper.special.length}][4] = {${specialRows(upper.special)}};
static const u32 porf_lower_special[${lower.special.length}][4] = {${specialRows(lower.special)}};
static const u32 porf_cased_ranges[${cased.length}][2] = {${rangeRows(cased)}};
static const u32 porf_case_ignorable_ranges[${ignorable.length}][2] = {${rangeRows(ignorable)}};
`;

const here = dirname(fileURLToPath(import.meta.url));
fs.writeFileSync(join(here, 'case_tables.js'), `// generated by compiler/gen_case_tables.js: do not edit\nexport default ${JSON.stringify(c)};\n`);
console.log(`upper runs ${upperRuns.length}, lower runs ${lowerRuns.length}, upper special ${upper.special.length}, lower special ${lower.special.length}, cased ${cased.length}, case-ignorable ${ignorable.length}`);
if (upper.special.some(x => x.length > 4) || lower.special.some(x => x.length > 4)) throw new Error('a special mapping longer than 3 code points');
