// Writes the index tables the legacy decoders read (runtime/encoding/index-*.mjs) from the
// Encoding Standard's indexes (https://encoding.spec.whatwg.org/indexes.json). A build tool
// run by hand under Node, not part of the runtime:
//
//   node runtime/encoding/generate.mjs [indexes.json]   (fetched from the spec without one)
//
// Each index is a string, one UTF-16 unit per pointer: a lookup is a charCodeAt, and the
// table is data in the program, not a big array literal built at startup. A pointer the index
// has no code point for is U+FFFD (no index maps a pointer to U+FFFD itself). Big5's
// code points outside the BMP (all on plane 2) keep their low 16 bits in the table and set a
// bit in a second string, 16 pointers to a unit.

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

const SPEC = 'https://encoding.spec.whatwg.org/indexes.json';
const here = import.meta.dirname;
const indexes = process.argv[2]
	? JSON.parse(readFileSync(process.argv[2], 'utf8'))
	: await (await globalThis.fetch(SPEC)).json();

const SINGLE_BYTE = [
	'ibm866',
	'iso-8859-2',
	'iso-8859-3',
	'iso-8859-4',
	'iso-8859-5',
	'iso-8859-6',
	'iso-8859-7',
	'iso-8859-8',
	'iso-8859-10',
	'iso-8859-13',
	'iso-8859-14',
	'iso-8859-15',
	'iso-8859-16',
	'koi8-r',
	'koi8-u',
	'macintosh',
	'windows-874',
	'windows-1250',
	'windows-1251',
	'windows-1252',
	'windows-1253',
	'windows-1254',
	'windows-1255',
	'windows-1256',
	'windows-1257',
	'windows-1258',
	'x-mac-cyrillic'
];

// a unit written as itself: a visible character, not a mark that joins the one before it
const VISIBLE = /^[\p{L}\p{N}\p{P}\p{S}]$/u;
const MARK = /^\p{M}$/u;

/** A JS string literal of UTF-16 units, the visible ones as themselves. */
function literal(units) {
	let out = "'";

	for (const unit of units) {
		const char = String.fromCharCode(unit);

		if (char === "'" || char === '\\') out += `\\${char}`;
		else if (unit < 0xd800 || unit > 0xdfff) {
			if (VISIBLE.test(char) && !MARK.test(char) && unit !== 0xfffd && unit < 0xe000) out += char;
			else out += `\\u${unit.toString(16).padStart(4, '0')}`;
		} else out += `\\u${unit.toString(16).padStart(4, '0')}`;
	}

	return `${out}'`;
}

/** An index's units: its code points' low 16 bits, U+FFFD for none. */
function units(index) {
	return index.map((cp) => (cp === null ? 0xfffd : cp & 0xffff));
}

const HEADER =
	"// Generated by runtime/encoding/generate.mjs from the Encoding Standard's indexes\n" +
	'// (https://encoding.spec.whatwg.org/indexes.json): do not edit.\n\n';

/** Writes one generated module. */
function write(file, body) {
	writeFileSync(join(here, file), HEADER + body);
	console.log('wrote', file);
}

write(
	'index-single-byte.mjs',
	"/** Each single-byte encoding's code points for bytes 0x80 to 0xFF, by name (U+FFFD: none). */\n" +
		'export const SINGLE_BYTE_INDEXES = {\n' +
		SINGLE_BYTE.map((name) => `\t'${name}': ${literal(units(indexes[name]))}`).join(',\n') +
		'\n};\n'
);

for (const [name, what] of [
	['jis0208', 'JIS X 0208 (EUC-JP, ISO-2022-JP, Shift_JIS)'],
	['jis0212', 'JIS X 0212 (EUC-JP)'],
	['euc-kr', 'EUC-KR'],
	['gb18030', 'gb18030 and GBK, two-byte sequences']
]) {
	const id = name.replace('-', '_').toUpperCase();

	if (indexes[name].some((cp) => cp !== null && cp > 0xffff)) throw new Error(`${name}: not BMP`);
	write(
		`index-${name}.mjs`,
		`/** Index ${name}: ${what}. A code point per pointer, U+FFFD for none. */\n` +
			`export const INDEX_${id} = ${literal(units(indexes[name]))};\n`
	);
}

// gb18030's four-byte ranges: pointer and code point pairs
const ranges = indexes['gb18030-ranges'];

write(
	'index-gb18030-ranges.mjs',
	'/** Index gb18030 ranges: the pointers where a run of code points starts. */\n' +
		`export const RANGE_POINTERS = [${ranges.map(([pointer]) => pointer).join(', ')}];\n\n` +
		'/** The code point each run starts at. */\n' +
		`export const RANGE_CODE_POINTS = [${ranges.map(([, cp]) => cp).join(', ')}];\n`
);

// Big5: plane 2 marked by a bitset, a bit per pointer
const big5 = indexes.big5;
const astral = new Array(Math.ceil(big5.length / 16)).fill(0);

big5.forEach((cp, pointer) => {
	if (cp === null || cp <= 0xffff) return;
	if (cp >> 16 !== 2) throw new Error('big5: a code point outside planes 0 and 2');
	astral[pointer >> 4] |= 1 << (pointer & 15);
});
write(
	'index-big5.mjs',
	'/** Index Big5: a code point per pointer (its low 16 bits), U+FFFD for none. */\n' +
		`export const INDEX_BIG5 = ${literal(units(big5))};\n\n` +
		'/** Which pointers are on plane 2: bit (pointer & 15) of unit (pointer >> 4). */\n' +
		`export const BIG5_PLANE_2 = ${literal(astral)};\n`
);
